# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JiaGeXianForiPone' do
	pod 'MKNetworkKit', '~> 0.87'
end

target 'JiaGeXianForiPoneTests' do

end

target 'JiaGeXianForiPoneUITests' do

end

